global:
  no_diag: 0
  log:
    level: debug
  retry: 3
  interval: 3
  exclude_no_result_test: 0

test:
  - module: HTTP
    name: HTTP Test
    config:
      retry: 1
      content: It works!
    role: web

result_filter:
  - module: Status

format:
  - module: Text
    filter:
      module: Status
      status: not ok

format_filter:
  - module: Type

publish:
  - module: Term
    filter:
      module: Type
      type: text/plain
    
hosts:
  web:
    - svn.mizzy.org
    - trac.mizzy.org
