global:
  no_diag: 0
  log:
    level: debug
  retry: 3
  interval: 3

test:
  - module: HTTP
    name: HTTP Test
    config:
      retry: 1
      content: It works!
    role: web

format:
  - module: HTML
    config:
      css_uri: htmlmatrix.css

publish:
  - module: Term
    
hosts:
  web:
    - svn.mizzy.org
    - trac.mizzy.org
